### ISSUE TITLE
Won't launch

### ISSUE THREAD

**Issue by gajatko** [nosan/cassandra-test-spring-boot-samples#21]
The sample project didn't start. The same happened on my own project when I've just added dependencies from README of embedded-cassandra project

openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-3ubuntu1, mixed mode)

I wouldn't like to downgrade to 2014th Java 8 as some people suggest (the project wouldn't even compile due to using current Java APIs) ( https://stackoverflow.com/questions/46944788/cant-start-cassandra-single-node-cluster-on-centos7/46969714#46969714 )
```
/home/jacek/idea/jbr/bin/java -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -javaagent:/home/jacek/idea/lib/idea_rt.jar=41667:/home/jacek/idea/bin -Dfile.encoding=UTF-8 -classpath /home/jacek/IdeaProjects/embedded-cassandra-spring-boot-samples/target/classes:/home/jacek/.m2/repository/org/springframework/boot/spring-boot-starter/2.2.8.RELEASE/spring-boot-starter-2.2.8.RELEASE.jar:/home/jacek/.m2/repository/org/springframework/boot/spring-boot/2.2.8.RELEASE/spring-boot-2.2.8.RELEASE.jar:/home/jacek/.m2/repository/org/springframework/spring-context/5.2.7.RELEASE/spring-context-5.2.7.RELEASE.jar:/home/jacek/.m2/repository/org/springframework/spring-aop/5.2.7.RELEASE/spring-aop-5.2.7.RELEASE.jar:/home/jacek/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.2.8.RELEASE/spring-boot-autoconfigure-2.2.8.RELEASE.jar:/home/jacek/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.2.8.RELEASE/spring-boot-starter-logging-2.2.8.RELEASE.jar:/home/jacek/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar:/home/jacek/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar:/home/jacek/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.12.1/log4j-to-slf4j-2.12.1.jar:/home/jacek/.m2/repository/org/apache/logging/log4j/log4j-api/2.12.1/log4j-api-2.12.1.jar:/home/jacek/.m2/repository/org/slf4j/jul-to-slf4j/1.7.30/jul-to-slf4j-1.7.30.jar:/home/jacek/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar:/home/jacek/.m2/repository/org/springframework/spring-core/5.2.7.RELEASE/spring-core-5.2.7.RELEASE.jar:/home/jacek/.m2/repository/org/springframework/spring-jcl/5.2.7.RELEASE/spring-jcl-5.2.7.RELEASE.jar:/home/jacek/.m2/repository/org/yaml/snakeyaml/1.25/snakeyaml-1.25.jar:/home/jacek/.m2/repository/org/springframework/boot/spring-boot-starter-data-cassandra/2.2.8.RELEASE/spring-boot-starter-data-cassandra-2.2.8.RELEASE.jar:/home/jacek/.m2/repository/org/springframework/spring-tx/5.2.7.RELEASE/spring-tx-5.2.7.RELEASE.jar:/home/jacek/.m2/repository/org/springframework/spring-beans/5.2.7.RELEASE/spring-beans-5.2.7.RELEASE.jar:/home/jacek/.m2/repository/org/springframework/data/spring-data-cassandra/2.2.8.RELEASE/spring-data-cassandra-2.2.8.RELEASE.jar:/home/jacek/.m2/repository/org/springframework/spring-expression/5.2.7.RELEASE/spring-expression-5.2.7.RELEASE.jar:/home/jacek/.m2/repository/org/springframework/data/spring-data-commons/2.2.8.RELEASE/spring-data-commons-2.2.8.RELEASE.jar:/home/jacek/.m2/repository/com/datastax/cassandra/cassandra-driver-core/3.7.2/cassandra-driver-core-3.7.2.jar:/home/jacek/.m2/repository/io/netty/netty-handler/4.1.50.Final/netty-handler-4.1.50.Final.jar:/home/jacek/.m2/repository/io/netty/netty-common/4.1.50.Final/netty-common-4.1.50.Final.jar:/home/jacek/.m2/repository/io/netty/netty-resolver/4.1.50.Final/netty-resolver-4.1.50.Final.jar:/home/jacek/.m2/repository/io/netty/netty-buffer/4.1.50.Final/netty-buffer-4.1.50.Final.jar:/home/jacek/.m2/repository/io/netty/netty-transport/4.1.50.Final/netty-transport-4.1.50.Final.jar:/home/jacek/.m2/repository/io/netty/netty-codec/4.1.50.Final/netty-codec-4.1.50.Final.jar:/home/jacek/.m2/repository/com/google/guava/guava/19.0/guava-19.0.jar:/home/jacek/.m2/repository/io/dropwizard/metrics/metrics-core/4.1.9/metrics-core-4.1.9.jar:/home/jacek/.m2/repository/com/github/jnr/jnr-ffi/2.1.7/jnr-ffi-2.1.7.jar:/home/jacek/.m2/repository/com/github/jnr/jffi/1.2.16/jffi-1.2.16.jar:/home/jacek/.m2/repository/com/github/jnr/jffi/1.2.16/jffi-1.2.16-native.jar:/home/jacek/.m2/repository/org/ow2/asm/asm/5.0.3/asm-5.0.3.jar:/home/jacek/.m2/repository/org/ow2/asm/asm-commons/5.0.3/asm-commons-5.0.3.jar:/home/jacek/.m2/repository/org/ow2/asm/asm-analysis/5.0.3/asm-analysis-5.0.3.jar:/home/jacek/.m2/repository/org/ow2/asm/asm-tree/5.0.3/asm-tree-5.0.3.jar:/home/jacek/.m2/repository/org/ow2/asm/asm-util/5.0.3/asm-util-5.0.3.jar:/home/jacek/.m2/repository/com/github/jnr/jnr-x86asm/1.0.2/jnr-x86asm-1.0.2.jar:/home/jacek/.m2/repository/com/github/jnr/jnr-posix/3.0.44/jnr-posix-3.0.44.jar:/home/jacek/.m2/repository/com/github/jnr/jnr-constants/0.9.9/jnr-constants-0.9.9.jar:/home/jacek/.m2/repository/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar:/home/jacek/.m2/repository/com/github/nosan/embedded-cassandra-spring-boot-starter/2.0.5/embedded-cassandra-spring-boot-starter-2.0.5.jar:/home/jacek/.m2/repository/com/github/nosan/embedded-cassandra-spring-boot-autoconfigure/2.0.5/embedded-cassandra-spring-boot-autoconfigure-2.0.5.jar:/home/jacek/.m2/repository/com/github/nosan/embedded-cassandra/3.0.3/embedded-cassandra-3.0.3.jar:/home/jacek/.m2/repository/com/github/nosan/embedded-cassandra-api/3.0.3/embedded-cassandra-api-3.0.3.jar:/home/jacek/.m2/repository/com/github/nosan/embedded-cassandra-annotations/3.0.3/embedded-cassandra-annotations-3.0.3.jar:/home/jacek/.m2/repository/com/github/nosan/embedded-cassandra-commons/3.0.3/embedded-cassandra-commons-3.0.3.jar:/home/jacek/.m2/repository/org/apache/commons/commons-compress/1.20/commons-compress-1.20.jar com.example.cassandra.cassandra.CassandraApplication

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.8.RELEASE)

2020-07-07 15:24:37.700  INFO 56432 --- [           main] c.e.c.cassandra.CassandraApplication     : Starting CassandraApplication on bottesini with PID 56432 (/home/jacek/IdeaProjects/embedded-cassandra-spring-boot-samples/target/classes started by jacek in /home/jacek/IdeaProjects/embedded-cassandra-spring-boot-samples)
2020-07-07 15:24:37.702  INFO 56432 --- [           main] c.e.c.cassandra.CassandraApplication     : No active profile set, falling back to default profiles: default
2020-07-07 15:24:37.892  INFO 56432 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Reactive Cassandra repositories in DEFAULT mode.
2020-07-07 15:24:37.909  INFO 56432 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 14ms. Found 0 Reactive Cassandra repository interfaces.
2020-07-07 15:24:37.913  INFO 56432 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Cassandra repositories in DEFAULT mode.
2020-07-07 15:24:37.921  INFO 56432 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 8ms. Found 1 Cassandra repository interfaces.
2020-07-07 15:24:38.013  INFO 56432 --- [           main] c.g.n.e.cassandra.EmbeddedCassandra      : Starts EmbeddedCassandra[name='cassandra-1', version='3.11.6']
2020-07-07 15:24:38.096  INFO 56432 --- [           main] c.g.nosan.embedded.cassandra.RunProcess  : Run a command '/tmp/apache-cassandra-3.11.6-1937134457514705858/bin/cassandra -f -R' within the directory '/tmp/apache-cassandra-3.11.6-1937134457514705858' using the environment {JVM_EXTRA_OPTS=-Dcassandra.native_transport_port=33839 -Dcassandra.rpc_port=37449 -Dcassandra.storage_port=34991 -Dcassandra.jmx.local.port=44753 -Dcassandra.config=file:///tmp/apache-cassandra-3.11.6-1937134457514705858/conf/1663167055882201726-cassandra.yaml, JAVA_HOME=/home/jacek/idea/jbr}
2020-07-07 15:24:38.103  INFO 56432 --- [           main] c.g.n.e.c.EmbeddedCassandraDatabase      : EmbeddedCassandraDatabase[name='cassandra-1', version='3.11.6', node=UnixCassandraNode[pid='56499', exitValue='not exited']] has been started
2020-07-07 15:24:38.292  INFO 56432 --- [    cassandra-1] embeddedCassandra                        : [0.000s][warning][gc] -Xloggc is deprecated. Will use -Xlog:gc:/tmp/apache-cassandra-3.11.6-1937134457514705858/bin/../logs/gc.log instead.
2020-07-07 15:24:38.294  INFO 56432 --- [    cassandra-1] embeddedCassandra                        : intx ThreadPriorityPolicy=42 is outside the allowed range [ 0 ... 1 ]
2020-07-07 15:24:38.294  INFO 56432 --- [    cassandra-1] embeddedCassandra                        : Improperly specified VM option 'ThreadPriorityPolicy=42'
2020-07-07 15:24:38.294  INFO 56432 --- [    cassandra-1] embeddedCassandra                        : Error: Could not create the Java Virtual Machine.
2020-07-07 15:24:38.294  INFO 56432 --- [    cassandra-1] embeddedCassandra                        : Error: A fatal exception has occurred. Program will exit.
2020-07-07 15:24:38.314  WARN 56432 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedCassandra' defined in class path resource [com/github/nosan/boot/autoconfigure/embedded/cassandra/CassandraConfiguration.class]: Invocation of init method failed; nested exception is com.github.nosan.embedded.cassandra.api.CassandraException: Unable to start EmbeddedCassandra[name='cassandra-1', version='3.11.6']
2020-07-07 15:24:38.318  INFO 56432 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-07-07 15:24:38.323 ERROR 56432 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedCassandra' defined in class path resource [com/github/nosan/boot/autoconfigure/embedded/cassandra/CassandraConfiguration.class]: Invocation of init method failed; nested exception is com.github.nosan.embedded.cassandra.api.CassandraException: Unable to start EmbeddedCassandra[name='cassandra-1', version='3.11.6']
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:893) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.8.RELEASE.jar:2.2.8.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.8.RELEASE.jar:2.2.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.8.RELEASE.jar:2.2.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.8.RELEASE.jar:2.2.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.8.RELEASE.jar:2.2.8.RELEASE]
	at com.example.cassandra.cassandra.CassandraApplication.main(CassandraApplication.java:31) ~[classes/:na]
Caused by: com.github.nosan.embedded.cassandra.api.CassandraException: Unable to start EmbeddedCassandra[name='cassandra-1', version='3.11.6']
	at com.github.nosan.embedded.cassandra.EmbeddedCassandra.doStart(EmbeddedCassandra.java:151) ~[embedded-cassandra-3.0.3.jar:na]
	at com.github.nosan.embedded.cassandra.EmbeddedCassandra.start(EmbeddedCassandra.java:64) ~[embedded-cassandra-3.0.3.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1922) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1864) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	... 15 common frames omitted
Caused by: java.io.IOException: 'UnixCassandraNode[pid='56499', exitValue='1']' is not alive. Please see logs for more details
	Error: A fatal exception has occurred. Program will exit.
	Error: Could not create the Java Virtual Machine.
	Improperly specified VM option 'ThreadPriorityPolicy=42'
	intx ThreadPriorityPolicy=42 is outside the allowed range [ 0 ... 1 ]
	[0.000s][warning][gc] -Xloggc is deprecated. Will use -Xlog:gc:/tmp/apache-cassandra-3.11.6-1937134457514705858/bin/../logs/gc.log instead.
	at com.github.nosan.embedded.cassandra.EmbeddedCassandraDatabase.await(EmbeddedCassandraDatabase.java:238) ~[embedded-cassandra-3.0.3.jar:na]
	at com.github.nosan.embedded.cassandra.EmbeddedCassandraDatabase.start(EmbeddedCassandraDatabase.java:117) ~[embedded-cassandra-3.0.3.jar:na]
	at com.github.nosan.embedded.cassandra.EmbeddedCassandra.doStart(EmbeddedCassandra.java:145) ~[embedded-cassandra-3.0.3.jar:na]
	... 23 common frames omitted
```

**Comment by nosan** [comment]
Apache Cassandra does not support **Java 11.** You should either use **Java 8** or Apache Cassandra **4.0-alpha4**.

**Comment by nosan** [comment]
You can register `EmbeddedCassandraFactory` bean with being set`4.0-alpha4` version. This should help you :)

**Comment by nosan** [comment]
https://nosan.github.io/embedded-cassandra/#configure-version

https://nosan.github.io/embedded-cassandra/#configure-custom-cassandra-factory-4

**Comment by gajatko** [comment]
Thanks, I hope it will become a stable version ASAP :)
